# Generated by Django 2.1.5 on 2019-03-02 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 19, 25, 14, 525260)),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 19, 25, 14, 525199)),
        ),
    ]
